### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by baarkerlounger** [Grollicus/geoclue_fake#1]
Aside from `cargo build` and `cargo run` what else is needed to get geoclue to use this as it's location source?

**Comment by Grollicus** [comment]
This (somewhat) implements geoclue's dbus interface, it is meant as a *replacement* for geoclue.

If you're on arch, here's a pkgbuild to install it https://github.com/Grollicus/geoclue_fake-install/blob/master/PKGBUILD

Check out the `package()`-function, it copies all the supplementary files. Mainly the config file to `/etc/geoclue_fake.toml` (or provide the config file path as command line argument).
